javac -cp mahout-core-0.5.jar:mahout-math-0.5.jar:mahout-utils-0.5.jar:commons-math-2.2.jar name/Validation.java name/CPLOPConnection.java name/DetectMachineError.java
java -cp mysqlj.jar:mahout-math-0.5.jar:. name.DetectMachineError
